import uuid
from flask import Flask, request, jsonify, render_template
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

from config import (
    RATE_LIMIT, THRESHOLD_AI, THRESHOLD_HUMAN, MIN_RELIABLE_WORDS, CERT_MAX_CONFIDENCE
)
from classifier import classify_llm
from stylometrics import classify_stylometric
from lexical import classify_lexical
from code_analyzer import classify_code_llm, classify_code_stylometric
from scorer import combine_scores, attribution_from_score
import auditor
import store

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

VALID_CONTENT_TYPES = {"text", "code"}


# ---------------------------------------------------------------------------
# Label generation
# ---------------------------------------------------------------------------

def _build_label(confidence: float) -> dict:
    pct = round(confidence * 100)
    if confidence >= THRESHOLD_AI:
        return {
            "status": "ai_generated",
            "display_text": (
                f"This content was likely generated by an AI. Our system's confidence is {pct}%. "
                "AI-assisted or AI-generated content may not reflect the lived experience or "
                "original voice of the attributed creator. If you are the creator and believe "
                "this classification is wrong, you may submit an appeal using your content ID."
            ),
            "confidence_pct": pct,
        }
    elif confidence <= THRESHOLD_HUMAN:
        return {
            "status": "human",
            "display_text": (
                f"This content appears to be human-authored. Our system's confidence is {pct}%. "
                "Our analysis found stylistic and semantic patterns consistent with human writing. "
                "No further review is required — this label may be updated if an appeal is filed."
            ),
            "confidence_pct": pct,
        }
    else:
        return {
            "status": "uncertain",
            "display_text": (
                f"Attribution uncertain. Our system's confidence is {pct}%. "
                "Our analysis could not determine with confidence whether this content is "
                "human-authored or AI-generated. The result should be treated as inconclusive. "
                "If you are the creator, you may submit an appeal with supporting context."
            ),
            "confidence_pct": pct,
        }


# ---------------------------------------------------------------------------
# POST /submit
# ---------------------------------------------------------------------------

@app.route("/submit", methods=["POST"])
@limiter.limit(RATE_LIMIT)
def submit():
    body = request.get_json(silent=True)
    if not body:
        return jsonify({"error": "Request body must be JSON."}), 400

    text = body.get("text", "").strip()
    creator_id = body.get("creator_id", "").strip()
    content_type = body.get("content_type", "text").strip().lower()

    if not text:
        return jsonify({"error": "Missing required field: text"}), 400
    if not creator_id:
        return jsonify({"error": "Missing required field: creator_id"}), 400
    if content_type not in VALID_CONTENT_TYPES:
        return jsonify({"error": f"content_type must be one of: {sorted(VALID_CONTENT_TYPES)}"}), 400

    content_id = body.get("content_id") or str(uuid.uuid4())[:8]
    word_count = len(text.split())
    text_too_short = word_count < MIN_RELIABLE_WORDS

    # --- Detection pipeline (branches by content_type) ---
    if content_type == "code":
        llm_result = classify_code_llm(text)
        stylo_result = classify_code_stylometric(text)
    else:
        llm_result = classify_llm(text)
        stylo_result = classify_stylometric(text)

    llm_score = llm_result["score"]
    stylo_score = stylo_result["score"]

    # Signal 3: lexical (text only — not meaningful for code)
    if content_type == "text":
        lex_result = classify_lexical(text)
        lex_score = lex_result["score"]
    else:
        lex_result = {"score": 0.5, "features": {"note": "not applicable for code"}}
        lex_score = 0.5

    confidence = combine_scores(llm_score, stylo_score, lex_score)
    attribution = attribution_from_score(confidence)
    label = _build_label(confidence)

    record = {
        "content_id": content_id,
        "creator_id": creator_id,
        "content_type": content_type,
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": round(llm_score, 4),
        "stylometric_score": round(stylo_score, 4),
        "lexical_score": round(lex_score, 4),
        "text_too_short": text_too_short,
        "status": "classified",
        "llm_reasoning": llm_result["reasoning"],
    }
    store.save(content_id, record)

    auditor.log_classification(
        content_id=content_id,
        creator_id=creator_id,
        attribution=attribution,
        confidence=confidence,
        llm_score=llm_score,
        stylometric_score=stylo_score,
        lexical_score=lex_score,
        content_type=content_type,
        text_too_short=text_too_short,
    )

    response = {
        "content_id": content_id,
        "content_type": content_type,
        "attribution": attribution,
        "confidence": confidence,
        "signals": {
            "llm_judge": {
                "score": round(llm_score, 4),
                "label": llm_result["label"],
                "reasoning": llm_result["reasoning"],
            },
            "stylometric": {
                "score": round(stylo_score, 4),
                "features": stylo_result.get("features"),
            },
            "lexical": {
                "score": round(lex_score, 4),
                "features": lex_result.get("features"),
            },
        },
        "label": label,
        "text_too_short": text_too_short,
    }
    if text_too_short:
        response["warning"] = f"Text is {word_count} words. Scores are unreliable below {MIN_RELIABLE_WORDS} words."

    return jsonify(response), 200


# ---------------------------------------------------------------------------
# POST /appeal
# ---------------------------------------------------------------------------

@app.route("/appeal", methods=["POST"])
def appeal():
    body = request.get_json(silent=True)
    if not body:
        return jsonify({"error": "Request body must be JSON."}), 400

    content_id = body.get("content_id", "").strip()
    creator_reasoning = body.get("creator_reasoning", "").strip()

    if not content_id:
        return jsonify({"error": "Missing required field: content_id"}), 400
    if len(creator_reasoning) < 10:
        return jsonify({"error": "creator_reasoning must be at least 10 characters."}), 400

    record = store.get(content_id)
    if record is None:
        return jsonify({"error": f"content_id '{content_id}' not found."}), 404

    store.update_status(content_id, "under_review")

    auditor.log_appeal(
        content_id=content_id,
        creator_reasoning=creator_reasoning,
        original_attribution=record["attribution"],
        original_confidence=record["confidence"],
    )

    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "original_attribution": record["attribution"],
        "original_confidence": record["confidence"],
        "message": "Your appeal has been received and flagged for human review. No automated re-classification will occur.",
    }), 200


# ---------------------------------------------------------------------------
# POST /certify  [STRETCH: provenance certificate]
# ---------------------------------------------------------------------------

@app.route("/certify", methods=["POST"])
def certify():
    """
    Issue a 'Verified Human' certificate to a creator.

    The creator provides a short written statement about their creative process.
    The system runs that statement through the detection pipeline. If it scores
    as human (confidence <= CERT_MAX_CONFIDENCE), a certificate is issued and
    attached to the original content record.

    This does not re-classify the original content — it adds a creator-verified
    layer on top of the system's existing attribution.
    """
    body = request.get_json(silent=True)
    if not body:
        return jsonify({"error": "Request body must be JSON."}), 400

    content_id = body.get("content_id", "").strip()
    creator_statement = body.get("creator_statement", "").strip()

    if not content_id:
        return jsonify({"error": "Missing required field: content_id"}), 400
    if len(creator_statement) < 30:
        return jsonify({"error": "creator_statement must be at least 30 characters."}), 400

    record = store.get(content_id)
    if record is None:
        return jsonify({"error": f"content_id '{content_id}' not found."}), 404

    if record.get("attribution") == "ai_generated":
        return jsonify({
            "error": "Certificates cannot be issued for content classified as ai_generated. File an appeal first.",
            "content_id": content_id,
        }), 422

    if record.get("certificate"):
        return jsonify({
            "message": "A certificate has already been issued for this content.",
            "certificate": record["certificate"],
        }), 200

    # Run creator statement through detection pipeline
    stmt_llm = classify_llm(creator_statement)
    stmt_stylo = classify_stylometric(creator_statement)
    stmt_lex = classify_lexical(creator_statement)
    stmt_confidence = combine_scores(stmt_llm["score"], stmt_stylo["score"], stmt_lex["score"])

    if stmt_confidence > CERT_MAX_CONFIDENCE:
        return jsonify({
            "error": "Certificate denied. Your written statement did not show sufficient human writing signals.",
            "statement_confidence": round(stmt_confidence, 4),
            "threshold": CERT_MAX_CONFIDENCE,
            "tip": "Write naturally about your creative process — describe your inspiration, drafting experience, or specific decisions you made. Formal or structured statements may score as AI-like.",
        }), 422

    certificate_id = "cert-" + str(uuid.uuid4())[:8]
    certificate = {
        "certificate_id": certificate_id,
        "content_id": content_id,
        "creator_id": record["creator_id"],
        "issued_at": auditor._now(),
        "statement_confidence": round(stmt_confidence, 4),
        "display_text": (
            "Verified Human — This content has been verified as human-authored through "
            "Provenance Guard's creator verification process. The creator provided a written "
            f"statement that scored {round((1 - stmt_confidence) * 100)}% human confidence."
        ),
    }

    store.attach_certificate(content_id, certificate)
    auditor.log_certificate(
        content_id=content_id,
        creator_id=record["creator_id"],
        certificate_id=certificate_id,
        statement_confidence=stmt_confidence,
    )

    return jsonify({
        "content_id": content_id,
        "status": "verified_human",
        "certificate": certificate,
    }), 200


# ---------------------------------------------------------------------------
# GET /analytics  [STRETCH: analytics dashboard]
# ---------------------------------------------------------------------------

@app.route("/analytics", methods=["GET"])
def analytics():
    """
    Aggregate statistics over all audit log entries.

    Returns:
    - total_submissions: classification events logged
    - attribution_breakdown: count + percentage per attribution category
    - appeal_rate: appeals / total_submissions
    - avg_confidence_by_attribution: mean confidence for each attribution category
    - certificates_issued: count of provenance certificates
    - content_type_breakdown: text vs code submissions
    """
    entries = auditor.get_log(limit=10000)

    classifications = [e for e in entries if e.get("event_type") == "classification"]
    appeals = [e for e in entries if e.get("event_type") == "appeal"]
    certs = [e for e in entries if e.get("event_type") == "certificate_issued"]

    total = len(classifications)
    appeal_count = len(appeals)

    breakdown: dict[str, dict] = {}
    confidence_sums: dict[str, list] = {}
    type_counts: dict[str, int] = {}

    for c in classifications:
        attr = c.get("attribution", "unknown")
        breakdown[attr] = breakdown.get(attr, {"count": 0})
        breakdown[attr]["count"] += 1

        confidence_sums.setdefault(attr, []).append(c.get("confidence", 0))

        ctype = c.get("content_type", "text")
        type_counts[ctype] = type_counts.get(ctype, 0) + 1

    for attr, data in breakdown.items():
        data["pct"] = round(data["count"] / total * 100, 1) if total else 0

    avg_confidence = {
        attr: round(sum(scores) / len(scores), 4)
        for attr, scores in confidence_sums.items()
    }

    return jsonify({
        "total_submissions": total,
        "attribution_breakdown": breakdown,
        "avg_confidence_by_attribution": avg_confidence,
        "appeal_rate": round(appeal_count / total, 4) if total else 0,
        "appeals_filed": appeal_count,
        "certificates_issued": len(certs),
        "content_type_breakdown": type_counts,
    }), 200


# ---------------------------------------------------------------------------
# GET /dashboard  [STRETCH: visual analytics view]
# ---------------------------------------------------------------------------

@app.route("/dashboard", methods=["GET"])
def dashboard():
    return render_template("dashboard.html")


# ---------------------------------------------------------------------------
# GET /log
# ---------------------------------------------------------------------------

@app.route("/log", methods=["GET"])
def get_log():
    limit = request.args.get("limit", 20, type=int)
    event_type = request.args.get("event_type")
    entries = auditor.get_log(limit=limit * 3 if event_type else limit)
    if event_type:
        entries = [e for e in entries if e.get("event_type") == event_type][-limit:]
    return jsonify({"entries": entries, "count": len(entries)}), 200


# ---------------------------------------------------------------------------

if __name__ == "__main__":
    app.run(debug=True, port=5001)
