from groq import Groq
from config import GROQ_API_KEY, LLM_MODEL

_client = Groq(api_key=GROQ_API_KEY)

_SYSTEM = """You are an AI content attribution classifier. Your job is to evaluate whether a piece of creative writing was written by a human or generated by an AI language model.

Analyze the submitted text for these characteristics of AI-generated writing:
- Unnaturally consistent tone and register throughout
- Absence of genuine hedging, self-contradiction, or uncertainty
- Formulaic openings or transitions ("In the realm of...", "As the sun...")
- Balanced, symmetrical paragraph structure that feels optimized rather than composed
- Fluency that is technically correct but emotionally flat or generic
- Avoidance of idiosyncratic phrasing, personal tangents, or irrelevant detail

Human writing tends to: vary in energy across a piece, hedge or contradict itself, use distinctive personal voice, include unexpected tangents, and show signs of real-world constraints (running out of ideas, changing tack mid-sentence).

Respond with ONLY these three lines — no other text:
Label: <ai_generated|human>
Score: <float between 0.0 and 1.0, where 1.0 = certain AI, 0.0 = certain human>
Reasoning: <one sentence explaining the most decisive signal>"""


def classify_llm(text: str) -> dict:
    """
    Signal 1: LLM-as-judge classification.

    Returns:
        {
            "label": "ai_generated" | "human",
            "score": float (0.0–1.0, where 1.0 = strong AI signal),
            "reasoning": str
        }

    Falls back to {"label": "uncertain", "score": 0.5, "reasoning": "..."} on error.
    """
    try:
        response = _client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": _SYSTEM},
                {"role": "user", "content": f"Classify this text:\n\n{text}"},
            ],
            temperature=0,
        )
        raw = response.choices[0].message.content.strip()

        label = None
        score = None
        reasoning = "No reasoning provided."

        for line in raw.splitlines():
            line = line.strip()
            if line.lower().startswith("label:"):
                label = line.split(":", 1)[1].strip().lower()
            elif line.lower().startswith("score:"):
                try:
                    score = float(line.split(":", 1)[1].strip())
                except ValueError:
                    pass
            elif line.lower().startswith("reasoning:"):
                reasoning = line.split(":", 1)[1].strip()

        if label not in ("ai_generated", "human") or score is None:
            return {"label": "uncertain", "score": 0.5, "reasoning": "Parse error — defaulting to uncertain."}

        score = max(0.0, min(1.0, score))
        return {"label": label, "score": score, "reasoning": reasoning}

    except Exception as e:
        return {"label": "uncertain", "score": 0.5, "reasoning": f"API error — defaulting to uncertain: {e}"}
