import re
from groq import Groq
from config import GROQ_API_KEY, LLM_MODEL

_client = Groq(api_key=GROQ_API_KEY)

_CODE_SYSTEM = """You are an AI code attribution classifier. Evaluate whether the submitted code was written by a human developer or generated by an AI coding assistant (GitHub Copilot, ChatGPT, Claude, etc.).

Characteristics of AI-generated code:
- Overly complete: every edge case handled, comprehensive docstrings on every function
- Formulaic: consistent patterns that feel templated, not evolved through iteration
- Comment style: explains WHAT every line does rather than WHY a decision was made
- Naming: perfectly consistent conventions with no abbreviations or shortcuts
- No debugging residue: no commented-out experiments, no TODO/FIXME/HACK notes
- Logic that is correct but academic — optimized for clarity over real-world constraints

Characteristics of human-written code:
- Inconsistent style: varying conventions, occasional shortcuts
- Sparse, strategic comments: notes explain intent or workarounds, not mechanics
- Debugging traces: commented-out experiments, TODO notes, temporary hacks
- Naming: occasionally abbreviated, shortened, or domain-idiosyncratic
- Imperfect edges: sometimes messy around boundary conditions

Respond with ONLY these three lines — no other text:
Label: <ai_generated|human>
Score: <float between 0.0 and 1.0, where 1.0 = certain AI, 0.0 = certain human>
Reasoning: <one sentence explaining the most decisive signal>"""


def classify_code_llm(code: str) -> dict:
    """Signal 1 for code content type. Same contract as classify_llm()."""
    try:
        response = _client.chat.completions.create(
            model=LLM_MODEL,
            messages=[
                {"role": "system", "content": _CODE_SYSTEM},
                {"role": "user", "content": f"Classify this code:\n\n{code}"},
            ],
            temperature=0,
        )
        raw = response.choices[0].message.content.strip()

        label, score, reasoning = None, None, "No reasoning provided."
        for line in raw.splitlines():
            line = line.strip()
            if line.lower().startswith("label:"):
                label = line.split(":", 1)[1].strip().lower()
            elif line.lower().startswith("score:"):
                try:
                    score = float(line.split(":", 1)[1].strip())
                except ValueError:
                    pass
            elif line.lower().startswith("reasoning:"):
                reasoning = line.split(":", 1)[1].strip()

        if label not in ("ai_generated", "human") or score is None:
            return {"label": "uncertain", "score": 0.5, "reasoning": "Parse error."}

        return {"label": label, "score": round(max(0.0, min(1.0, score)), 4), "reasoning": reasoning}

    except Exception as e:
        return {"label": "uncertain", "score": 0.5, "reasoning": f"API error: {e}"}


def classify_code_stylometric(code: str) -> dict:
    """
    Code-specific stylometric signal.

    Measures:
    - Comment density: comment lines / total lines. AI = high comment density.
    - Line length variance: AI code has more uniform line lengths.
    - Docstring presence: ratio of functions that have docstrings. AI = near 1.0.
    - Debug residue absence: no TODO/FIXME/HACK/commented-out code. AI = clean.
    """
    lines = code.splitlines()
    non_empty = [l for l in lines if l.strip()]
    if len(non_empty) < 3:
        return {"score": 0.5, "features": {"note": "too short"}}

    # Comment density
    comment_lines = sum(1 for l in non_empty if l.strip().startswith("#"))
    comment_density = comment_lines / len(non_empty)
    # AI: high comment density (0.3+). Human: sparser comments.
    comment_score = min(1.0, comment_density / 0.30)

    # Line length variance (lower variance = more uniform = AI-like)
    lengths = [len(l) for l in non_empty]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    # variance above 600 = human-like (wide variation). Below 100 = AI-like.
    line_var_score = max(0.0, 1.0 - variance / 600.0)

    # Debug residue (TODO/FIXME/HACK/commented-out code = human signal)
    debug_markers = {"todo", "fixme", "hack", "xxx", "note:", "temp", "kludge"}
    has_debug = any(
        any(m in l.lower() for m in debug_markers)
        for l in lines
    )
    debug_score = 0.0 if has_debug else 1.0  # clean code = AI-like

    # Docstring presence (look for triple-quoted strings after def lines)
    def_lines = [i for i, l in enumerate(lines) if re.match(r'\s*def ', l)]
    if def_lines:
        docstring_count = sum(
            1 for i in def_lines
            if i + 1 < len(lines) and '"""' in lines[i + 1]
        )
        docstring_ratio = docstring_count / len(def_lines)
    else:
        docstring_ratio = 0.5  # neutral if no functions found

    docstring_score = docstring_ratio  # high docstring coverage = AI-like

    combined = (
        comment_score * 0.30
        + line_var_score * 0.30
        + debug_score * 0.25
        + docstring_score * 0.15
    )

    return {
        "score": round(max(0.0, min(1.0, combined)), 4),
        "features": {
            "comment_density_score": round(comment_score, 4),
            "line_variance_score": round(line_var_score, 4),
            "debug_absence_score": round(debug_score, 4),
            "docstring_score": round(docstring_score, 4),
            "raw": {
                "total_lines": len(non_empty),
                "comment_lines": comment_lines,
                "comment_density": round(comment_density, 4),
                "line_length_variance": round(variance, 2),
                "has_debug_markers": has_debug,
                "functions_found": len(def_lines),
            },
        },
    }
